// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbhmakrijnqirefjlnva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiaG1ha3Jpam5xaXJlZmpsbnZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTkzNTQsImV4cCI6MjA3Mzc5NTM1NH0.BclehlqJnZVu7GRu1PKs3O573Ebd6GtPcUqic2huqN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});